$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: __ENDPOINT_NAME__
model: __MODEL_REFERENCE__
model_mount_path: /var/ue-model
environment: azureml:ue-rating-py314:1
instance_type: Standard_DS2_v2
instance_count: 1
app_insights_enabled: true

data_collector:
  sampling_rate: 1.0
  rolling_rate: Minute
  collections:
    model_inputs:
      enabled: true
    model_outputs:
      enabled: true
